import { images } from "@/lib/images";
import type { CatalogProduct } from "@/lib/shopify/mappers";

export const localProducts: CatalogProduct[] = [
  {
    id: "local-midnight-bronze-spiral",
    handle: "midnight-bronze-spiral",
    title: "Midnight Bronze Spiral",
    description:
      "Designed for the intentional creator, the Midnight Bronze Spiral balances a robust tactile feel with an effortless aesthetic. Features a heavyweight midnight blue cover and a signature aged-bronze binding that opens perfectly flat.",
    price: "$32.00",
    priceAmount: 32,
    currencyCode: "INR",
    image: images.designer,
    images: [
      images.designer,
      images.spiralBinding,
      images.openPages,
      images.stackedSpiral,
    ],
    detail: "Navy Linen • A5",
    badge: "Bestseller",
    category: "Spiral",
    tags: ["spiral", "softcover", "notebook", "bestseller"],
    edition: "softcover",
    available: true,
    options: [],
    variants: [
      {
        id: "local-midnight-bronze-spiral-default",
        title: "Default",
        available: true,
        price: "$32.00",
        options: [],
      },
    ],
    source: "local",
  },
  {
    id: "local-archival-hardcover",
    handle: "the-archival-hardcover",
    title: "The Archival Hardcover",
    description: "Navy linen hardcover notebook with gold foil stamping.",
    price: "$34.00",
    priceAmount: 34,
    currencyCode: "INR",
    image: images.designer,
    images: [images.designer],
    detail: "Navy Linen • A5",
    badge: "Bestseller",
    category: "Hardcover",
    tags: ["hardcover", "notebook", "bestseller"],
    edition: "hardcover",
    available: true,
    options: [],
    variants: [
      {
        id: "local-archival-hardcover-default",
        title: "Default",
        available: true,
        price: "$34.00",
        options: [],
      },
    ],
    source: "local",
  },
  {
    id: "local-daily-softcover",
    handle: "the-daily-softcover",
    title: "The Daily Softcover",
    description: "Tan leather softcover for everyday notes.",
    price: "$28.00",
    priceAmount: 28,
    currencyCode: "INR",
    image: images.dailySoftcover,
    images: [images.dailySoftcover],
    detail: "Tan Leather • A5",
    badge: "New Release",
    category: "Softcover",
    tags: ["softcover", "notebook"],
    edition: "softcover",
    available: true,
    options: [],
    variants: [
      {
        id: "local-daily-softcover-default",
        title: "Default",
        available: true,
        price: "$28.00",
        options: [],
      },
    ],
    source: "local",
  },
  {
    id: "local-celestial-nocturne",
    handle: "celestial-nocturne",
    title: "Celestial Nocturne",
    description: "Limited edition midnight blue cloth cover with constellation foil.",
    price: "$42.00",
    priceAmount: 42,
    currencyCode: "INR",
    image: images.celestial,
    images: [images.celestial],
    detail: "Midnight Blue • A5",
    badge: "Limited Edition",
    category: "Special Editions",
    tags: ["special", "limited-edition", "hardcover"],
    edition: "special",
    available: true,
    options: [],
    variants: [
      {
        id: "local-celestial-nocturne-default",
        title: "Default",
        available: true,
        price: "$42.00",
        options: [],
      },
    ],
    source: "local",
  },
  {
    id: "local-sage-hardcover",
    handle: "classic-sage-hardcover",
    title: "Classic Sage Hardcover",
    description: "A sage green minimalist notebook with a premium matte cover.",
    price: "$28.00",
    priceAmount: 28,
    currencyCode: "INR",
    image: images.sageHardcover,
    images: [images.sageHardcover],
    detail: "Sage • A5",
    category: "Hardcover",
    tags: ["hardcover"],
    edition: "hardcover",
    available: true,
    options: [],
    variants: [
      {
        id: "local-sage-hardcover-default",
        title: "Default",
        available: true,
        price: "$28.00",
        options: [],
      },
    ],
    source: "local",
  },
  {
    id: "local-linen-ivory",
    handle: "linen-ivory-personal",
    title: "Linen Ivory Personal",
    description: "Ivory linen notebook with personalized gold leaf lettering.",
    price: "$45.00",
    priceAmount: 45,
    currencyCode: "INR",
    image: images.linenIvory,
    images: [images.linenIvory],
    detail: "Ivory Linen • A5",
    category: "Personalized",
    tags: ["hardcover", "special"],
    edition: "special",
    available: true,
    options: [],
    variants: [
      {
        id: "local-linen-ivory-default",
        title: "Default",
        available: true,
        price: "$45.00",
        options: [],
      },
    ],
    source: "local",
  },
];

export function getLocalProduct(handle: string) {
  return localProducts.find((product) => product.handle === handle);
}

export function getLocalProducts() {
  return localProducts;
}
